spring:
  liquibase:
    url: jdbc:postgresql://localhost:5432/rsnotesdb
    user: rsnotes
    password: rsnotes
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/rsnotesdb
    username: rsnotes
    password: rsnotes
  webflux:
    hiddenmethod:
      filter:
        enabled: true
