services:
  postgres:
    build: ./postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - ./postgres/initdb/${POSTGRES_PROFILE}:/docker-entrypoint-initdb.d:ro
  redis:
    image: "redis:alpine"
    ports:
      - "${REDIS_PORT}:6379"
