version: "3"
services:
  postgres:
    build: .
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - ./postgres/initdb/${POSTGRES_PROFILE}:/docker-entrypoint-initdb.d:ro
